import Head from "next/head";



export default function Home() {
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Teddy Bear Finds A Dad Whod Never" />
        <meta property="og:type" content="articals" />
        <meta property="og:url" content="https://next-articals.vercel.app/articaltow" />
        <meta
          property="og:image"
          content="https://lolitopia.com/wp-content/uploads/2021/07/4-12.jpeg"
        />
        <meta property="og:site_name" content="infoanimalscare" />
        <meta
          property="og:description"
          content="The foster family attempted to take a photo of Ellie without her teddy bear, but she snuggled in concern. When they provided it back to her, she got it as if to never release again."
        />
       
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway"
        />
      </Head>

      <h1>Artical Two</h1>
     </div>
  );
}
